# Dockerfile
# Use the official NGINX image as the base
FROM nginx:latest

# Copy a custom NGINX configuration file, if needed
# COPY nginx.conf /etc/nginx/nginx.conf

# Expose the port NGINX will listen on
EXPOSE 80
