apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cloudlens
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: tls-secret
          mountPath: /etc/nginx/ssl
          readOnly: true
      volumes:
      - name: html-volume
        configMap:
          name: nginx-html-config
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: tls-secret
        secret:
          secretName: nginx-tls-secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-config
data:
  index.html: |
    <html>
    <head>
        <title>Welcome</title>
        <style>
            body {
                display: flex;
                flex-direction: column;
                justify-content: flex-start; /* Align to the top */
                align-items: center; /* Center horizontally */
                height: 100vh;
                margin: 0;
                font-family: Arial, sans-serif;
            }
            h1 {
                font-size: 48px;
                font-weight: bold;
                margin-top: 20px; /* Adjust spacing from the top */
            }
        </style>
    </head>
    <body>
        <h1>Welcome to ExtraHop K8s Demo</h1>
    </body>
    </html>


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        # Redirect HTTP to HTTPS
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name _;

        ssl_certificate /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
