apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: open-webui-deployment-7d5b87ff85
  namespace: open-webui
  labels:
    app: open-webui
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: open-webui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: open-webui
    spec:
      volumes:
        - name: webui-volume
          persistentVolumeClaim:
            claimName: open-webui-pvc
        - name: volume1
          hostPath:
            path: /var/log
            type: Directory
        - name: volume2
          hostPath:
            path: /
            type: Directory
        - name: volume3
          hostPath:
            path: /lib/modules
            type: Directory
        - name: volume4
          hostPath:
            path: /var/run/docker.sock
            type: Socket
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:main
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: OLLAMA_BASE_URL
              value: http://ollama-service.open-webui.svc.cluster.local:11434
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500Mi
          volumeMounts:
            - name: webui-volume
              mountPath: /app/backend/data
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          tty: true
        - name: sidecar
          image: sec-cloudlens.departmentofdemos.com/sensor
          args:
            - '--auto_update'
            - 'y'
            - '--project_key'
            - c853712ca3364efe8bc4fd549b03b4d0
            - '--accept_eula'
            - 'yes'
            - '--server'
            - sec-cloudlens.departmentofdemos.com
            - '--custom_tags'
            - platform=k8s
            - '--ssl_verify no'
          resources: {}
          volumeMounts:
            - name: volume1
              mountPath: /var/log/cloudlens
            - name: volume2
              mountPath: /host
            - name: volume3
              mountPath: /lib/modules
            - name: volume4
              mountPath: /var/run/containerd/containerd.sock
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - “SYS_MODULE”
                - “SYS_RESOURCE”
                - “NET_RAW”
                - “NET_ADMIN”
            allowPrivilegeEscalation: true