stages:
  - aws-auth

aws-login:
  stage: aws-auth
  image: amazon/aws-cli
  script:
    - echo "Testing AWS authentication..."
    - aws sts get-caller-identity
    - aws s3 ls || true  # Prevent error if no buckets exist
