azure-auth-check:
  stage: test
  image: mcr.microsoft.com/azure-cli
  script:
    - echo "Logging in to Azure..."
    - az login --service-principal -u "$AZURE_CLIENT_ID" -p "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"
    - az account show
