gcp-auth-check:
  stage: test
  image: google/cloud-sdk:slim
  script:
    - echo "$GCP_SERVICE_ACCOUNT_KEY" > gcp-key.json
    - gcloud auth activate-service-account --key-file=gcp-key.json
    - gcloud config set project poc-project-463913
    - gcloud auth list
    - gcloud projects describe poc-project-463913
