# Ansible Inventory - Generated by Terraform

[ubuntu_vms]
%{ for name, vm in ubuntu_vms ~}
${name} ansible_host=${vm.public_ip != null ? vm.public_ip : vm.private_ip} ansible_user=${ssh_username}
%{ endfor ~}

[redhat_vms]
%{ for name, vm in rhel_vms ~}
${name} ansible_host=${vm.public_ip != null ? vm.public_ip : vm.private_ip} ansible_user=${ssh_username}
%{ endfor ~}

[windows]
%{ for name, vm in windows_vms ~}
${name} ansible_host=${vm.public_ip != null ? vm.public_ip : vm.private_ip}
%{ endfor ~}

[clms]
clms-vm ansible_host=${clms_vm.public_ip != null ? clms_vm.public_ip : clms_vm.private_ip} ansible_user=${ssh_username}

[linux:children]
ubuntu_vms
redhat_vms
clms

[all:children]
linux
windows

# Linux Variables
[linux:vars]
ansible_ssh_private_key_file=${ssh_private_key}
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# Windows Variables
[windows:vars]
ansible_user=${windows_username}
ansible_password=${windows_password}
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_port=5985

# Common Variables
[all:vars]
ansible_python_interpreter=/usr/bin/python3