# Production-specific values for my-app-chart
# This overrides the default values.yaml

# Use your private registry
image:
  repository: us-west2-docker.pkg.dev/poc-project-463913/brinek-registry/my-app
  tag: "1.0.0"
  pullPolicy: Always

# Image pull secrets for private registry
imagePullSecrets:
  - name: gcr-secret

# Production replicas
replicaCount: 3

# Production domain
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: my-app.prod.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: my-app-prod-tls
      hosts:
        - my-app.prod.example.com

# Production resources
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Production autoscaling
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

# Production environment variables
env:
  - name: APP_ENV
    value: "production"
  - name: LOG_LEVEL
    value: "warn"
  - name: ENABLE_PROFILING
    value: "false"

# Production node selector
nodeSelector:
  node-role.kubernetes.io/worker: "true"
  node-type: "primary"

# Production tolerations
tolerations: []

# Production affinity - spread across zones
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - my-app
      topologyKey: topology.kubernetes.io/zone

# Production PDB
podDisruptionBudget:
  enabled: true
  minAvailable: 2

# Production monitoring
serviceMonitor:
  enabled: true
  interval: 15s

# Production namespace
namespace:
  create: true
  name: my-app-prod
